"""initial schema

Revision ID: e294c00c8bf7
Revises: 
Create Date: 2026-03-03 22:28:27.531305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e294c00c8bf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_urls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('viewports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=False),
    sa.Column('full_page', sa.Boolean(), nullable=False),
    sa.Column('archive_enabled', sa.Boolean(), nullable=False),
    sa.Column('dismiss_cookies', sa.Boolean(), nullable=False),
    sa.Column('change_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_urls_url'), 'monitored_urls', ['url'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('capture_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('viewport_label', sa.Text(), nullable=False),
    sa.Column('viewport_width', sa.Integer(), nullable=False),
    sa.Column('viewport_height', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['monitored_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_jobs_status'), 'capture_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_capture_jobs_url_id'), 'capture_jobs', ['url_id'], unique=False)
    op.create_table('captures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('viewport_label', sa.Text(), nullable=False),
    sa.Column('viewport_width', sa.Integer(), nullable=False),
    sa.Column('viewport_height', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('archive_path', sa.Text(), nullable=True),
    sa.Column('archive_size', sa.Integer(), nullable=True),
    sa.Column('diff_image_path', sa.Text(), nullable=True),
    sa.Column('diff_score', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', 'TIMEOUT', name='capturestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['monitored_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_captured_at'), 'captures', ['captured_at'], unique=False)
    op.create_index(op.f('ix_captures_url_id'), 'captures', ['url_id'], unique=False)
    op.create_table('url_tags',
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['url_id'], ['monitored_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('url_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_tags')
    op.drop_index(op.f('ix_captures_url_id'), table_name='captures')
    op.drop_index(op.f('ix_captures_captured_at'), table_name='captures')
    op.drop_table('captures')
    op.drop_index(op.f('ix_capture_jobs_url_id'), table_name='capture_jobs')
    op.drop_index(op.f('ix_capture_jobs_status'), table_name='capture_jobs')
    op.drop_table('capture_jobs')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_monitored_urls_url'), table_name='monitored_urls')
    op.drop_table('monitored_urls')
    op.execute("DROP TYPE IF EXISTS jobstatus")
    op.execute("DROP TYPE IF EXISTS capturestatus")
    # ### end Alembic commands ###
